<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-12 12:53
=======
# Generated by Django 4.2 on 2023-04-12 12:50
>>>>>>> feature/templates/post

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Posting_app', '0001_initial'),
=======
        ("Posting_app", "0001_initial"),
>>>>>>> feature/templates/post
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='postingcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postingcomment',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posting_app.posting'),
        ),
        migrations.AddField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            model_name="postingcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="postingcomment",
            name="posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Posting_app.posting"
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
>>>>>>> feature/templates/post
        ),
    ]
