# Generated by Django 4.2 on 2023-04-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posting_app", "0002_remove_posting_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="content",
            field=models.CharField(max_length=248, verbose_name="글 내용"),
        ),
        migrations.AlterField(
            model_name="posting",
            name="title",
            field=models.CharField(max_length=50, verbose_name="글 제목"),
        ),
    ]
